### ISSUE TITLE
Whale Chase Fix Explained (Finished)

### ISSUE THREAD

**Issue by LighteningXL** [LighteningXL/SADX-Whale-Chase-Fix#1]
Here it is! Finalized and done! No more updates.
http://www.megafileupload.com/26h25/SA_WhaleChase_FIX.zip

____Changelog 4/9/17____
- Moved the 9th Dash Panel slightly to the right to avoid clipping toward the left side where he meets the first jump ramp.
(Position Z – change from 1756.69 to 1757.4)

____Changelog 4/9/17____
- Fixed 4th dash panel from having incorrect scale and speed value.
(Scale change from 10, 120, 0  to  11, 0, 0)
(Speed change from 10  to  11)

____Changelog 4/8/17____
- supercoolsonic's fixed jump ramp for deathless spindash included
- Changed Right Pushy Wall Scale/Variable from 420, 90, 0 to 384, 90, 0 for stricter match to the Dreamcast

____Optional No-Jump Version____
http://www.megafileupload.com/26h4r/Whale_Chase_Fix_No-Jump_Version.rar
- Changed 2nd Dash Panel's speed from 10 to 10.8
- Moved 5th & 6th Dash Panel to the left by a smidge’ to avoid missing the panels in this version.
(5th Dash Panel's Position X – change from 4300.81 to 4302.81)
(6th Dash Panel's Position X – change from 4300.81 to 4301.81)

**So what happened?**
Back then even with the correct dashpad values from SA Dreamcast (despite the 4th dash panel value being incorrect in the previous SET from SETFixes hotfix zip before), there used to be funky problems with the Whale Chase that was causing a couple of slowdowns, giving the Whale an advantage to hit Sonic into the backside to death.
![untitled-1](https://cloud.githubusercontent.com/assets/26220489/24841471/8bfa5ec6-1d53-11e7-876d-61c12a5b2269.gif)
![aff3e708-1c12-11e7-8e65-3348f9191cd4](https://cloud.githubusercontent.com/assets/26220489/24841351/83e46cf2-1d50-11e7-9885-e9f3ee18505b.gif)
![f3a2d382-1c13-11e7-8133-8712acf5e97a](https://cloud.githubusercontent.com/assets/26220489/24841352/8895d0ba-1d50-11e7-8a55-93341965da79.gif)

All of this was because of the Left/Right Pushy Walls interacting his speed during the run and midair. All that was needed was for both Left and Right Pushy Walls' Scale/Variables to be adjusted. What I did was this.

Right Pushy Wall Scale/Variable – changed from 820, 90, 0 to 384, 90, 0
Left Pushy Wall Scale/Variable – changed from 641, 90, 0 to 384, 90, 0
![screenshot_20170408171718](https://cloud.githubusercontent.com/assets/26220489/24832813/29378124-1c86-11e7-8eb9-317067a20ac8.jpg)
![screenshot_20170408171242](https://cloud.githubusercontent.com/assets/26220489/24832814/2adcf568-1c86-11e7-8e56-5762cd5e1376.jpg)

I measured by the strongest push to weakest push in-game on Dreamcast.
![pixect-20170408163340](https://cloud.githubusercontent.com/assets/26220489/24832775/4fb5cef6-1c85-11e7-8e63-27e4a6b54fd1.jpg)
The way the left pushy wall works is opposite. This means that at the beginning of the road, the push starts off weakest and ends off strongest near the end of the road.
![pixect-20170408163825](https://cloud.githubusercontent.com/assets/26220489/24832777/57529f2c-1c85-11e7-8166-8bc5e3c82472.jpg)

Now it works the same as Dreamcast, but with supercoolsonic's jump ramp fix included to avoid death whilst spindashing. Everything else is kept like the SA1 dash pad values on the road except that the 4th dash pad value was incorrect, so I fixed it. SA1 values from 1st to 8th dash panel on the road. (11, 10, 10, 11, 7, 8, 7, 9)

You might've also found yourself slightly clipping toward the left side when meeting the first jump ramp at random times before. This happens on Dreamcast too.
It's fixed now.
![pixect-20170407211322](https://cloud.githubusercontent.com/assets/26220489/24888438/901b9bf8-1e31-11e7-86b4-db56d76183c7.jpg)
It's all due to how the walls are doing their job at certain times, because pushy walls have random behavior at aligning the player along the road. Then I ended up making a tidbit adjustment with the 9th Dash Panel's Position Z to avoid clipping.

There is also a specific way to hit the 3rd dash panel with no jump. You just have to hit the very lower left corner of the right side dash panel to do it.
![pixect-20170407010823](https://cloud.githubusercontent.com/assets/26220489/24832810/15a02b84-1c86-11e7-8e71-43d2464dd691.jpg)

I've compared my SET file from Dreamcast disc to make sure everything else is the same and not different. This is how I found out that the 4th dash panel's scale value was supposed to be 11, 0, 0 and speed value at 11. With this SET shall restore and fix everything about one of the most memorable moments of Sonic Adventure. So kick back, relax, enjoy and have fun, all!

**Comment by supercoolsonic** [comment]
Thank you. This'll make it a lot easier to keep track of. ....Hoookay. Alright. What's the values on the ramp in my layout? I know it isn't changed in the SADXFE layouts.

**Comment by LighteningXL** [comment]
Position – 4702.45, 6.74, 1687.58
Rotation – F500, FFD9, 0
Scale/Variables – 8, 60, 0

pretty much the same. hmm...

**Comment by supercoolsonic** [comment]
Can't be. It just can't be. I remember moving it slightly when making that layout while we were talking on Steam. Are you absolutely sure?

**Comment by LighteningXL** [comment]
Oh... THAT set. Hold on, I'll get it and look at it.

**Comment by supercoolsonic** [comment]
It won't lower it, but it'll bring it out a bit more. Normally, it's actually inside the edge of that pier just a little bit, and I believe making sure it's all the way out prevent Sonic from smacking his face on it.

**Comment by LighteningXL** [comment]
Here it is. Mine with your ramp values.

http://www.megafileupload.com/1qjqk/SET0100S.bin

It was just different position wise.

Changed from  4702.45, 6.74, 1687.58  to  4702.45, 6.74, 1685.38

**Comment by supercoolsonic** [comment]
Got it, and...well, I just tried spindashing through the segment, and Sonic didn't get caught by the whale after that ramp. I'd say it's good, now.

**Comment by LighteningXL** [comment]
Yep. Works nice. You should use this SET as your primary if you're going to make an update on Emerald Coast Act 1 again.

**Comment by supercoolsonic** [comment]
Hmmm....maybe. I'd still give you credit, but there's a few more things I need to tinker with in the section, but they don't include the dash panels or anything directly related to the sequence. Just some ring positioning, I believe. Once I get back to Emerald Coast, I'll consider it. And I also want to know what PkR thinks of a fully-functional and fixed layout like this.

**Comment by LighteningXL** [comment]
Thanks alot dude! I'm just glad that we've got the opportunity to fix one of the most memorable scenes of Sonic Adventure. It's one of my favorite moments throughout the game.

**Comment by Tea-Fox** [comment]
Found something interesting, when you run into the right boost pad at a certain point, you actually don't make a jump in the beginning, Sonic will just run.
I'm not sure exactly what that angle of the boost pad does to keep Sonic from jumping or if that could be used to adjust something.

**Comment by LighteningXL** [comment]
Yep. You can make it always happen on this corner of the right dashpad.
![pixect-20170407010823](https://cloud.githubusercontent.com/assets/26220489/24827539/bd2a70fc-1c19-11e7-9fa4-da521a756c62.png)

**Comment by LighteningXL** [comment]
- Changed Right Pushy Wall Scale/Variable from 420, 90, 0 to 384, 90, 0 for stricter match to the Dreamcast

**Comment by LighteningXL** [comment]
@supercoolsonic Err... I took my real Dreamcast SET0100S.BIN from disc and looked at it.

1) The walls are like what your Dreamcast SET were to be (long with the old Scale/Variable values). Funnily how they don't work the same way in DX since the whole road is super pushy unlike how it works on Dreamcast.

2) The 4th dash panel is 11. Err... We had it on 10 the whole time.

Looking into it a little more to make sure everything else is not different with the dashes on the road. Will keep you updated.

**Comment by LighteningXL** [comment]
@Tea-Fox Thank you for the giffys, Tea. 👍 I added them to my op post.

**Comment by Tea-Fox** [comment]
Cool. 
Hmm, Sonic moves definitely pretty much identical to the DC one now.
I wonder though, could the jump in the beginning still be fixed and everything else kept intact?

**Comment by LighteningXL** [comment]
Okey-dokey! Decided to fix random clip toward the left wall thing where he meets the first jump ramp. I guess having that happening wasn't necessarily.

http://www.megafileupload.com/26h25/SA_WhaleChase_FIX.zip

____Changelog 4/9/17____
-Moved the 9th Dash Panel slightly to the right to avoid clipping toward the left side where he meets the first jump ramp.
(Position Z – change from 1756.69 to 1757.4)


@Tea-Fox I prefer having the beginning jump the way it is I guess because it looks like the whale is going right up your alley and about to catch your rare end.

But if you want the 100% no jump, here you go. It just needed some slight adjustment with the 5th and 6th dash panel's X postion so he doesn't miss touching them in this version

http://www.megafileupload.com/26h26/SA_WhaleChase_FIX_(No_Jump).zip

____For No-Jump version____
-Changed 3rd Dash Panel speed from 10 to 10.67
-Moved the 5th and 6th Dash Panel slightly to the left to avoid missing the panels.
(5th Dash Panel's Position X – change from 4300.81 to 4302.81)
(5th Dash Panel's Position X – change from 4300.81 to 4301.81)

**Comment by Tea-Fox** [comment]
Awesome, works great! No deaths so far from testing. :)
The SET0100S.BIN file, is that only the Whale Chase Sequence or is that the whole SET for Emerald Coast? Hopefully the former.
Also I made a quick mod out of the file so it can be used and updated independently from the other SETfixes:
[http://www.megafileupload.com/26h4r/Whale_Chase_Fix_No-Jump_Version.rar](url)

**Comment by LighteningXL** [comment]
Thank you so much. A SET file is a whole level of a character. So for example: SET0100S.BIN is the whole level of Emerald Coast as Sonic.
SET0100E.BIN is the whole level of Emerald Coast as E-102.

**Comment by Tea-Fox** [comment]
That would mean you would have to update them every now and then to keep it up-to-date with the other SETfixes.
Hmm, would it be possible to make a SET that only updates the relevant part of the level? That way you wouldn't have to update everything.

**Comment by LighteningXL** [comment]
Unfortunately nope. Me not too savy with domain and cloud stuff, can't say for sure how to use the modmanager update feature. Maybe i'll manually up-to-date it the old fashion way with a link on the first post and a date added to the .zip name since EC1 hasn't received updates too often.

**Comment by LighteningXL** [comment]
Unfortunately nope. Me not too savy with domain and cloud stuff, can't say for sure how to use the modmanager update feature. Maybe i'll manually up-to-date it the old fashion way with a link on the first post and a date added to the .zip name since EC1 hasn't received updates too often anyway.

**Comment by LighteningXL** [comment]
@supercoolsonic Ciao, my friend… Here's letting you that the whale chase is all good and ready for take off. 

> **supercoolsonic commented:**
_I'd post it back over on the other topic, and just wait for him to give his opinion. I don't see why he wouldn't accept this._

I have no other words to say other than that whether you're right or wrong about something in life, it happens. We move on in the end. We're human.
Even if the author isn't, hey. I am all for [forgiveness](https://www.youtube.com/watch?v=13mUFEXnB54)…

Lastly, babe's finalized! No more updating anymore if [this](http://www.megafileupload.com/26h25/SA_WhaleChase_FIX.zip) will go part of your SETFixes.
Figuring out and fixing problems with this scene was a fun run while it lasted.

**Comment by LighteningXL** [comment]
@supercoolsonic Ciao, my friend… Here's letting you know that the whale chase is all good and ready for takeoff!

> **supercoolsonic commented:**
_I'd post it back over on the other topic, and just wait for him to give his opinion. I don't see why he wouldn't accept this._

I have no words to say other than whether who's right or wrong about something in life, it happens. We're human species. We move on in the end. Even if they aren't, hey! I am all for getting along and [forgiveness](https://www.youtube.com/watch?v=13mUFEXnB54)…
It's just one of the most memorable scenes out of this game. I just don't see why not. I was very serious about getting this actually right and then fixed. I've provided loads of evidence and explaining on what I've done.

Last I'll say, it's all fixed! No more updating god willing if [this](http://www.megafileupload.com/26h25/SA_WhaleChase_FIX.zip) goes part of your SETFixes. Figuring out and fixing issues with the scene was a fun run while it lasted… Take care!

**Comment by bradvaSchnitzelpj** [comment]
Not only have you violated the terms of Section I and Section L on Github, but your behavior has been an absolute annoyance to the project author and the community. You have been reported.
